version: '3.8'

services:
  study-planner-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study-planner-be
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '9001:3000'
