export const JWT_CONST = {
  JWT_ACCESS_EXPIRES_IN: 'JWT_ACCESS_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
  JWT_SECRET: 'JWT_SECRET',

  JWT_REFRESH_TOKEN_SUCCESS: 'Tokens refreshed successfully',
};
